# entrypoint: java -noverify BOOT-INF/resources/:BOOT-INF/classes/:BOOT-INF/lib/* mono.thainow.ThainowApplication

runtime: java11
instance_class: F2

env_variables:
  TWILIO_ACCOUNT_SID: AC717febc2f6f291c8e8d0eb6afe028074
  TWILIO_AUTH_TOKEN: 9ef54ffa6fd9a80d4b4692f2433e5c3f
  TWILIO_OTP_SERVICE_ID: VA3e5ee9be3da08b9bebe9ad236bd99d15


handlers:  
- url: (/api/.*)
  script: auto

# - url: (/.*)
#   static_files: BOOT-INF/classes/static\1
#   upload: BOOT-INF/classes/static/.*\.(gif|png|jpg|svg|ico|css|js|html|json)$
#   secure: optional

